"""
report_generator.py
Generates a clean 1-page PDF equity research report using fpdf2.
"""

from fpdf import FPDF
import io


BRAND_DARK  = (15,  25,  35)
BRAND_MID   = (26,  45,  69)
BRAND_LIGHT = (140, 168, 200)
GREEN       = (34,  84,  61)
RED         = (116, 42,  42)
AMBER       = (116, 98,  16)
GREY_BG     = (248, 249, 251)
GREY_LINE   = (226, 232, 240)
TEXT_MAIN   = (26,  32,  44)
TEXT_SUB    = (113, 128, 150)


def _s(text: str) -> str:
    """Sanitize text to latin-1 safe characters."""
    if not text:
        return ""
    text = str(text)
    result = ""
    for char in text:
        try:
            char.encode('latin-1')
            result += char
        except (UnicodeEncodeError, UnicodeDecodeError):
            replacements = {
                '\u2014': '-', '\u2013': '-', '\u2019': "'", '\u2018': "'",
                '\u201c': '"', '\u201d': '"', '\u2022': '*', '\u2026': '...',
                '\u00a0': ' ', '\u2011': '-', '\u2012': '-', '\u00b7': '.',
                '\u00e9': 'e', '\u00e8': 'e', '\u00e0': 'a', '\u00fc': 'u',
                '\u00f6': 'o', '\u00e4': 'a', '\u00df': 'ss',
            }
            result += replacements.get(char, '')
    return result


class EquityReport(FPDF):

    def header(self):
        self.set_fill_color(*BRAND_DARK)
        self.rect(0, 0, 210, 22, "F")
        self.set_y(5)
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(240, 230, 211)
        self.cell(0, 8, "EquityLens  |  AI-Powered Equity Research", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 7.5)
        self.set_text_color(*BRAND_LIGHT)
        self.cell(0, 4, "For informational purposes only - Not investment advice", new_x="LMARGIN", new_y="NEXT")
        self.ln(6)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*TEXT_SUB)
        self.cell(0, 5,
            "Generated by EquityLens - Data sourced from Yahoo Finance - This is not a solicitation to buy or sell securities.",
            align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*BRAND_MID)
        self.set_fill_color(*GREY_BG)
        self.cell(0, 6, f"  {title.upper()}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*BRAND_MID)
        self.line(self.l_margin, self.get_y(), 210 - self.r_margin, self.get_y())
        self.ln(2)

    def body_text(self, text: str, size=9):
        self.set_font("Helvetica", "", size)
        self.set_text_color(*TEXT_MAIN)
        self.multi_cell(0, 5, _s(text))
        self.ln(1)

    def metric_row(self, pairs: list):
        col_w = (210 - self.l_margin - self.r_margin) / len(pairs)
        start_x = self.l_margin
        y = self.get_y()
        for label, value in pairs:
            self.set_fill_color(*GREY_BG)
            self.set_draw_color(*GREY_LINE)
            self.rect(start_x, y, col_w - 2, 14, "FD")
            self.set_xy(start_x + 2, y + 1.5)
            self.set_font("Helvetica", "", 6.5)
            self.set_text_color(*TEXT_SUB)
            self.cell(col_w - 4, 4, _s(label).upper(), new_x="RIGHT", new_y="TOP")
            self.set_xy(start_x + 2, y + 6)
            self.set_font("Helvetica", "B", 9.5)
            self.set_text_color(*TEXT_MAIN)
            self.cell(col_w - 4, 6, _s(str(value)), new_x="RIGHT", new_y="TOP")
            start_x += col_w
        self.set_y(y + 16)

    def verdict_block(self, verdict: str, rationale: str):
        colors = {
            "BUY":       (GREEN, (240, 255, 244)),
            "HOLD":      (AMBER, (255, 255, 240)),
            "SELL":      (RED,   (255, 245, 245)),
            "UNCERTAIN": (TEXT_SUB, GREY_BG),
        }
        border_col, bg_col = colors.get(verdict, colors["UNCERTAIN"])
        y = self.get_y()
        h = 18
        self.set_fill_color(*bg_col)
        self.set_draw_color(*GREY_LINE)
        self.rect(self.l_margin, y, 190, h, "FD")
        self.set_fill_color(*border_col)
        self.rect(self.l_margin, y, 3, h, "F")
        icon = {"BUY": "BUY", "HOLD": "HOLD", "SELL": "SELL"}.get(verdict, "UNCERTAIN")
        self.set_xy(self.l_margin + 6, y + 2)
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*border_col)
        self.cell(22, 5, icon, new_x="RIGHT", new_y="TOP")
        self.set_xy(self.l_margin + 30, y + 2)
        self.set_font("Helvetica", "", 8.5)
        self.set_text_color(*TEXT_MAIN)
        self.multi_cell(156, 5, _s(rationale[:280]))
        self.set_y(y + h + 3)

    def risk_chips(self, risks: list):
        level_colors = {
            "HIGH":   (RED,   (253, 215, 215)),
            "MEDIUM": (AMBER, (254, 252, 191)),
            "LOW":    (GREEN, (198, 246, 213)),
        }
        y = self.get_y()
        for r in risks:
            level = r.get("level", "MEDIUM").upper()
            flag  = _s(r.get("flag", ""))
            bc, bg = level_colors.get(level, level_colors["MEDIUM"])
            self.set_xy(self.l_margin, y)
            self.set_fill_color(*bg)
            self.set_draw_color(*bc)
            self.rect(self.l_margin, y, 186, 6.5, "FD")
            self.set_xy(self.l_margin + 2, y + 0.8)
            self.set_font("Helvetica", "B", 6.5)
            self.set_text_color(*bc)
            self.cell(18, 5, f"[{level}]", new_x="RIGHT", new_y="TOP")
            self.set_xy(self.l_margin + 22, y + 0.8)
            self.set_font("Helvetica", "", 7)
            self.set_text_color(*TEXT_MAIN)
            self.cell(164, 5, flag[:90], new_x="RIGHT", new_y="TOP")
            y += 8
        self.set_y(y + 3)


def generate_pdf_report(
    ticker: str,
    company: str,
    sector: str,
    currency: str,
    price: str,
    financials: dict,
    analysis: dict,
    generated_at: str,
) -> bytes:

    pdf = EquityReport(orientation="P", unit="mm", format="A4")
    pdf.set_margins(12, 28, 12)
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.add_page()

    # Company title
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*BRAND_DARK)
    pdf.cell(0, 8, _s(f"{company}  ({ticker})"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(*TEXT_SUB)
    pdf.cell(0, 5, _s(f"{sector}  -  {currency}  -  Report date: {generated_at}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Metrics
    pdf.section_title("Key Metrics")
    pdf.metric_row([
        ("Current Price",  f"{currency} {price}"),
        ("P/E (TTM)",      financials.get("pe_ratio", "N/A")),
        ("EV/EBITDA",      financials.get("ev_ebitda", "N/A")),
        ("Debt/Equity",    financials.get("debt_equity", "N/A")),
    ])
    pdf.metric_row([
        ("Revenue Growth", financials.get("revenue_growth", "N/A")),
        ("Gross Margin",   financials.get("gross_margin", "N/A")),
        ("ROE",            financials.get("roe", "N/A")),
        ("52W Return",     financials.get("return_52w", "N/A")),
    ])
    pdf.metric_row([
        ("Market Cap",     financials.get("market_cap", "N/A")),
        ("Beta",           financials.get("beta", "N/A")),
        ("Dividend Yield", financials.get("dividend_yield", "N/A")),
        ("Free Cash Flow", financials.get("free_cash_flow", "N/A")),
    ])

    # Valuation
    pdf.section_title("Valuation Summary")
    pdf.body_text(analysis.get("valuation_summary", ""))

    # Verdict
    pdf.section_title("Analyst Verdict")
    pdf.verdict_block(
        analysis.get("verdict", "UNCERTAIN").upper(),
        analysis.get("verdict_rationale", "")
    )

    # Risks
    pdf.section_title("Risk Flags")
    pdf.risk_chips(analysis.get("risk_flags", []))

    # Positives
    pdf.section_title("Key Positives")
    for p in analysis.get("key_positives", []):
        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_text_color(*TEXT_MAIN)
        pdf.cell(6, 5, "+", new_x="RIGHT", new_y="TOP")
        pdf.set_x(pdf.l_margin + 6)
        pdf.multi_cell(0, 5, _s(p))
    pdf.ln(1)

    # Plain English
    pdf.section_title("Plain English Takeaway")
    pdf.set_fill_color(240, 248, 255)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(*BRAND_MID)
    pdf.multi_cell(0, 6, _s(analysis.get("plain_english", "")), fill=True)

    return bytes(pdf.output())
